In [15]:
# Importing the libraries
import pandas as pd
import numpy as np
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

In [16]:
# Reading and defining the dataset

df = pd.read_csv("Mealapp_dataset.csv", encoding='Latin-1')

In [17]:
df.head()

,Name,Customer_id,Customer_loc,Order_id,Vendor,Vendor_id,Vendor_lat,Vendor_long,Vendor_add,Category,...,Meal_name,Meal_category,Meal_price,Meal_description,Drink_id,Drink_category,Drink_name,Drink_price,Review,Rating
0,Philips Ema,2994,"Community road, 47",1a91337d-fe92-4411-9c90-6050a4fd2503,The Place,535724,6.51515,3.36925,"393 Herbert Macaulay Way, Sabo yaba, Lagos",Meal_category,...,Smokey Jollof Rice,Main Dishes,1600,Delicious Smokey Jollof Rice made with authent...,NaN,Ice Cream,Raspberry ripple,500,Unappetizing presentation. Won't order again.,2
1,Machado Antonio,6061,"Community road, 47",8648d0ae-eced-4f58-a294-dfd3bb42a155,Kinglace,899314,6.51515,3.36925,"390 Herbert Macaulay Way, Sabo yaba, Lagos",Meal_category,...,Beef Suya Skewers,Fish / Meats,800,Delicious Beef Suya Skewers made with authenti...,NaN,Juice / Carbonated Drink,Pepsi,300,Delicious food! Loved the flavors.,4
2,Jones Norah,7072,"Community road, 47",1b55c350-a080-467c-8cc8-91557a2500e5,SO FRESH,899314,6.51515,3.36925,"280 Herbert Macaulay Way, alagomeji Yaba, Lagos",Meal_category,...,Okra Soup with Garri,Vegetarian Dishes,2800,Delicious Okra Soup with Garri made with authe...,NaN,Ice Cream / Drink,Creole cream cheese,1000,Great service and quality. Highly recommend.,5
3,Gandhi Mahatma,4976,"Community road, 45",a8dfa612-fabb-4ffc-886f-e402ca7dfea5,SO FRESH,899314,6.51515,3.36925,"280 Herbert Macaulay Way, alagomeji Yaba, Lagos",Meal_category,...,Afang Soup with Fufu,Staple Food with Soups,2800,Delicious Afang Soup with Fufu made with authe...,NaN,Juice / Carbonated Drink,Pepsi,300,Unappetizing presentation. Won't order again.,2
4,Ip Regina,3991,"Community road, 48",53a1aa4a-169d-470b-b8fb-2be1068dea8b,Kinglace,899314,6.51515,3.36925,"390 Herbert Macaulay Way, Sabo yaba, Lagos",Drink_category,...,Ofada Rice and Stew with Assorted Meats,Specialties,2000,Delicious Ofada Rice and Stew with Assorted Me...,NaN,Ice Cream,Rocky Road,700,Fresh ingredients and authentic taste.,5

In [18]:
df = df[["Meal_description", "Meal_category", "Meal_name"]]

In [19]:
df.shape

(50000, 3)

In [20]:
df = df.sample(n=10000, replace=False, random_state=33).reset_index(drop=True, )

In [21]:
df.shape

(10000, 3)

In [22]:
df.head()

,Meal_description,Meal_category,Meal_name
0,Delicious Street Food / Snacks made with authe...,Appetizers,Street Food / Snacks
1,Delicious Prawn Stir-Fry with Rice made with a...,Seafood Delights,Prawn Stir-Fry with Rice
2,Delicious Fried Rice and BBQ Chicken made with...,Main Dishes,Fried Rice and BBQ Chicken
3,Delicious Grilled Fish with Plantain and Veggi...,Grilled Specialties,Grilled Fish with Plantain and Veggies
4,Delicious Ofada Rice and Stew with Assorted Me...,Specialties,Ofada Rice and Stew with Assorted Meats

In [40]:
df_ = df.drop_duplicates(["Meal_name"]).reset_index(drop=True)

df_.shape

(74, 4)

In [41]:
df_

,Meal_description,Meal_category,Meal_name,data
0,Delicious Street Food / Snacks made with authe...,Appetizers,Street Food / Snacks,delicious street food / snacks made with authe...
1,Delicious Prawn Stir-Fry with Rice made with a...,Seafood Delights,Prawn Stir-Fry with Rice,delicious prawn stir-fry with rice made with a...
2,Delicious Fried Rice and BBQ Chicken made with...,Main Dishes,Fried Rice and BBQ Chicken,delicious fried rice and bbq chicken made with...
3,Delicious Grilled Fish with Plantain and Veggi...,Grilled Specialties,Grilled Fish with Plantain and Veggies,delicious grilled fish with plantain and veggi...
4,Delicious Ofada Rice and Stew with Assorted Me...,Specialties,Ofada Rice and Stew with Assorted Meats,delicious ofada rice and stew with assorted me...
...,...,...,...,...
69,Delicious Chocolate Bread made with authentic ...,Desserts,Chocolate Bread,delicious chocolate bread made with authentic ...
70,Delicious Salad made with authentic Nigerian s...,Desserts,Salad,delicious salad made with authentic nigerian s...
71,Delicious Ofada Rice with Assorted Meats made ...,Local Delicacies,Ofada Rice with Assorted Meats,delicious ofada rice with assorted meats made ...
72,Delicious Stir Fry Pasta made with authentic N...,Delicacies,Stir Fry Pasta,delicious stir fry pasta made with authentic n...
73,Delicious White Rice and Beans with Grilled Tu...,Rice Dishes,White Rice and Beans with Grilled Turkey,delicious white rice and beans with grilled tu...

In [42]:
des = df_["Meal_description"]
cat = df_["Meal_category"]
meal = df_["Meal_name"]
data = []

for i in range(len(des)):
    str_ = "{} {} {}".format(des[i], cat[i], meal[i])
    data.append(str_.lower())

In [44]:
vec = TfidfVectorizer()
vec_ = vec.fit_transform(data)

In [45]:
sim = cosine_similarity(vec_)

In [46]:
df1 = pd.DataFrame(sim, columns=df_['Meal_name'], index=df_['Meal_name']).reset_index()
df1.head()

Meal_name,Meal_name,Street Food / Snacks,Prawn Stir-Fry with Rice,Fried Rice and BBQ Chicken,Grilled Fish with Plantain and Veggies,Ofada Rice and Stew with Assorted Meats,Chicken Suya Skewers,Egusi Soup with Pounded Yam,Grilled Beef Skewers with Spicy Sauce,Special Fried Rice,...,White Rice with Beans and Assorted meats,Starch with Banga Soup,Afang Soup with Fufu,Sweet Plantain Fritters,Coconut Curry Shrimp,Chocolate Bread,Salad,Ofada Rice with Assorted Meats,Stir Fry Pasta,White Rice and Beans with Grilled Turkey
0,Street Food / Snacks,1.000000,0.178917,0.209583,0.182148,0.196438,0.196561,0.308358,0.159350,0.211787,...,0.209016,0.196814,0.323553,0.214730,0.162783,0.207314,0.280056,0.179525,0.215307,0.179990
1,Prawn Stir-Fry with Rice,0.178917,1.000000,0.254376,0.190229,0.266769,0.195750,0.201438,0.167923,0.320315,...,0.311328,0.190306,0.211364,0.195853,0.449153,0.226803,0.255436,0.250944,0.457841,0.300889
2,Fried Rice and BBQ Chicken,0.209583,0.254376,1.000000,0.204471,0.284194,0.341425,0.180570,0.171038,0.488797,...,0.352934,0.218153,0.189468,0.229421,0.175507,0.223518,0.299217,0.256523,0.230037,0.397251
3,Grilled Fish with Plantain and Veggies,0.182148,0.190229,0.204471,1.000000,0.304689,0.317639,0.187363,0.572541,0.206622,...,0.220145,0.200477,0.196595,0.299365,0.165096,0.210260,0.260048,0.224866,0.199924,0.380934
4,Ofada Rice and Stew with Assorted Meats,0.196438,0.266769,0.284194,0.304689,1.000000,0.363699,0.202062,0.267594,0.351534,...,0.568113,0.216205,0.212019,0.215032,0.178049,0.226755,0.280450,0.688896,0.215609,0.329008

In [64]:
df1.to_csv("processed.csv", index=False)

In [101]:
import random

int_ = random.randint(0, 73)

query = df_["Meal_name"].unique()[int_]
query

'Chocolate Bread'

In [90]:
reco = pd.DataFrame(df1.nlargest(4, query)['Meal_name'])
reco = reco[reco['Meal_name']!=query]

In [91]:
", ".join(reco["Meal_name"])

'BBQ Chicken Wings with French Fries, Plantain Chips, Donut'

In [54]:
query

'Street Food / Snacks'

In [96]:
def recommend(text, num=4):
    reco = None
    reco = pd.DataFrame(df1.nlargest(num+1, query)['Meal_name'])
    reco = reco[reco['Meal_name']!=query]

    response = ", ".join(reco["Meal_name"])

    return response

In [98]:
recommend("Chicken wings", 3)

'BBQ Chicken Wings with French Fries, Plantain Chips, Donut'